name: farpy-deploy
on: workflow_dispatch

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sanitized bundle
        run: |
          set -euo pipefail
          rm -rf public && mkdir public
          date -u +"%Y-%m-%dT%H:%M:%SZ" \
            | awk '{print "{\"ok\":true,\"ts\":\""$1"\"}"}' > public/health.json
          echo "farpy public artifacts (auto-built)" > public/README.txt

      - name: Write SSH key from secret
        run: |
          set -euo pipefail
          printf '%s\n' "${{ secrets.SSH_KEY }}" > id_ci
          chmod 600 id_ci

      - name: Prove we can SSH (prints ok-from-ci)
        run: |
          set -euxo pipefail
          ssh -i id_ci -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'echo ok-from-ci'

      - name: Ensure remote folder exists (owned by deploy)
        run: |
          ssh -i id_ci -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            'sudo install -d -m 755 -o deploy -g deploy /opt/farpy/public'

      - name: Upload the bundle
        run: |
          scp -i id_ci -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new -r \
            public/* \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/farpy/public/

      - name: Verify on server
        run: |
          ssh -i id_ci -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            'ls -lah /opt/farpy/public && head -n3 /opt/farpy/public/health.json'
