- name: Install deps & build
  working-directory: frontend
  run: |
    npm install
    npm run build
- name: Ensure health.json exists
  run: |
    mkdir -p frontend/build
    echo "{\"ok\":true,\"ts\":\"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"}" > frontend/build/health.json
- name: Upload artifacts to server
  uses: wlixcc/SFTP-Deploy-Action@v1.2.4
  with:
    server: ${{ secrets.SSH_HOST }}
    username: ${{ secrets.SSH_USER }}
    ssh_private_key: ${{ secrets.SSH_KEY }}
    local_path: frontend/build/*
    remote_path: /opt/farpy/public
    sftp_only: true
    force_upload: true
