name: farpy-deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - "payouts.csv"   # adjust or remove if not needed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build (skip if no package.json)
        run: |
          if [ -f package.json ]; then
            npm ci
            npm run build
          else
            mkdir -p build
            echo '{"ok":true,"ts":"'$(date -u +%Y-%m-%dT%H:%M:%SZ)'" }' > build/health.json
          fi

      - name: Prepare SSH key (from base64)
        run: |
          echo "${{ secrets.SSH_KEY_B64 }}" | base64 -d > id_ed25519
          chmod 600 id_ed25519

      - name: Upload via SFTP (native client)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          sftp -i id_ed25519 -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST <<'SFTP'
          put -r build /opt/farpy/site/build
          bye
          SFTP
