name: farpy-deploy
on: workflow_dispatch

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build a tiny, strictly non-sensitive bundle
      - name: Build sanitized bundle
        run: |
          set -euxo pipefail
          rm -rf public
          mkdir -p public
          date -u +"%Y-%m-%dT%H:%M:%SZ" | awk '{print "{\"ok\":true,\"ts\":\""$1"\"}"}' > public/health.json
          printf "farpy public artifacts (auto-built)\n" > public/README.txt
          ls -lah public

      # Quick SSH smoke as the 'deploy' user
      - name: SSH smoke (whoami + list /opt/farpy/public)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          script: |
            set -euxo pipefail
            whoami
            ls -lah /opt/farpy/public || true

      # Copy the bundle; drop the leading "public/" and overwrite
      - name: SCP bundle to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          source:   "public/*"
          target:   "/opt/farpy/public"
          overwrite: true
          strip_components: 1
          debug: true
