name: farpy-deploy
on: workflow_dispatch

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (optional) mask just in case they ever appear in logs
      - name: Mask
        run: |
          echo "::add-mask::${{ secrets.HEALTH_KEY }}"
          echo "::add-mask::${{ secrets.FRONTEND_KEY }}"

      - name: Build tiny public bundle
        run: |
          set -euo pipefail
          rm -rf public && mkdir -p public
          date -u +"%Y-%m-%dT%H:%M:%SZ" | awk '{print "{\"ok\":true,\"ts\":\""$1"\"}"}' > public/health.json
          printf "farpy public artifacts (auto-built)\n" > public/README.txt

      - name: Write CI SSH key (exact)
        shell: bash
        run: |
          set -euo pipefail
          umask 077
          mkdir -p ~/.ssh
          cat > ~/.ssh/id_ci <<'KEY'
          ${{ secrets.SSH_KEY }}
          KEY
          chmod 600 ~/.ssh/id_ci

          # Show fingerprint of the private key’s public half (must match server)
          ssh-keygen -yf ~/.ssh/id_ci | ssh-keygen -lf - -E sha256 | awk '{print "ci-fp="$2}'

      - name: Prove we can SSH (prints ok-from-ci)
        run: |
          set -euo pipefail
          ssh -i ~/.ssh/id_ci -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new \
            -l "${{ secrets.SSH_USER }}" "${{ secrets.SSH_HOST }}" 'echo ok-from-ci'

      - name: Ensure /opt/farpy/public exists (deploy owns it)
        run: |
          set -euo pipefail
          ssh -i ~/.ssh/id_ci -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new \
            -l "${{ secrets.SSH_USER }}" "${{ secrets.SSH_HOST }}" \
            'install -d -m 755 -o deploy -g deploy /opt/farpy/public'

      - name: Upload the bundle (scp)
        run: |
          set -euo pipefail
          scp -i ~/.ssh/id_ci -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new -r \
            public/* "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/farpy/public/"

      - name: Verify on server
        run: |
          set -euo pipefail
          ssh -i ~/.ssh/id_ci -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new \
            -l "${{ secrets.SSH_USER }}" "${{ secrets.SSH_HOST }}" \
            'ls -lah /opt/farpy/public && head -n1 /opt/farpy/public/health.json'
