name: farpy-deploy
on: [workflow_dispatch, push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build sanitized artifacts (no secrets)
      - name: Build sanitized public files
        run: bash scripts/make-public.sh

      # Optional: mask known secrets if you ever echo them
      - run: |
          echo "::add-mask::${{ secrets.HEALTH_KEY }}"
          echo "::add-mask::${{ secrets.FRONTEND_KEY }}"

      # Copy sanitized artifacts to the host
      - name: Ship public/
        uses: appleboy/scp-action@v0.1.7
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          source:   "public/**"
          target:   "/opt/farpy/public"
