name: farpy-deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build (skip if no package.json)
        run: |
          ls -lah
          if [ -f package.json ]; then
            npm ci
            npm run build
          else
            echo "No package.json found -> shipping static build/ if present"
            mkdir -p build
          fi

      - name: Ensure health.json exists
        run: |
          mkdir -p build
          echo "{\"ok\":true,\"ts\":\"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"}" > build/health.json

      - name: Prepare SSH key (from base64)
        run: |
          echo "${{ secrets.SSH_KEY_B64 }}" | base64 -d > id_ed25519
          chmod 600 id_ed25519

      - name: Test SSH login
        run: |
          ssh -i id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "ls -lah | head -n 3"

      - name: Upload via SFTP (native client)
        run: |
          cat > sftp.batch <<'EOF'
          -mkdir /opt/farpy/public
          put -r build/* /opt/farpy/public
          EOF
          sftp -i id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} < sftp.batch

      - name: Verify live health
        run: |
          set -euo pipefail
          url="https://api.farpy.com/health?cb=$RANDOM"
          echo "GET $url"
          body="$(curl -fsS "$url" || true)"
          echo "$body"
          echo "$body" | grep -q '"ok":true'
