name: farpy-deploy
on: workflow_dispatch

concurrency:
  group: farpy-deploy
  cancel-in-progress: true

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build tiny public bundle
        shell: bash
        run: |
          set -euo pipefail
          rm -rf public && mkdir -p public
          date -u +"%Y-%m-%dT%H:%M:%SZ" | awk '{print "{\"ok\":true,\"ts\":\""$1"\"}"}' > public/health.json
          echo "farpy public artifacts (auto-built)" > public/README.txt
          ls -l public

      - name: Write SSH key from secret
        shell: bash
        run: |
          set -euo pipefail
          umask 077
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ci
          chmod 600 ~/.ssh/id_ci

      - name: Upload with SFTP (no shell, no legacy scp)
        shell: bash
        run: |
          set -euo pipefail
          printf '%s\n' \
            "put -p public/README.txt" \
            "put -p public/health.json" \
            "ls -l" \
          | sftp -vv -b - \
              -i ~/.ssh/id_ci \
              -o IdentitiesOnly=yes \
              -o StrictHostKeyChecking=accept-new \
              "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}"

      - name: Verify over HTTP
        shell: bash
        run: |
          set -euo pipefail
          curl -sS https://api.farpy.com/public/README.txt | head -n 1
          curl -sS https://api.farpy.com/public/health.json | head -n 1
