name: farpy-deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps & build
        run: |
          ls -lah
          if [ -f package.json ]; then
            npm install
            npm run build
          else
            echo "⚠️ No package.json found, skipping build"
            mkdir -p build
          fi

      - name: Ensure health.json exists
        run: |
          mkdir -p build
          echo "{\"ok\":true,\"ts\":\"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"}" > build/health.json

      - name: Upload artifacts to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
          local_path: build/*
          remote_path: /opt/farpy/public
          sftp_only: true
          force_upload: true
