name: farpy-deploy
on: workflow_dispatch

concurrency:
  group: farpy-deploy
  cancel-in-progress: true

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build tiny public bundle
        shell: bash
        run: |
          set -euo pipefail
          rm -rf public && mkdir -p public
          date -u +"%Y-%m-%dT%H:%M:%SZ" | awk '{print "{\"ok\":true,\"ts\":\""$1"\"}"}' > public/health.json
          echo "farpy public artifacts (auto-built)" > public/README.txt

      - name: Write SSH key from secret
        shell: bash
        run: |
          set -euo pipefail
          umask 077
          mkdir -p ~/.ssh
          cat > ~/.ssh/id_ci <<'KEY'
          ${{ secrets.SSH_KEY }}
          KEY
          chmod 600 ~/.ssh/id_ci

      - name: Upload with SFTP (ForceCommand-safe)
        shell: bash
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USER: ${{ secrets.SSH_USER }}
        run: |
          set -euo pipefail
          cat > batch.txt <<'B'
          cd /opt/farpy/public
          put -p public/README.txt
          put -p public/health.json
          ls -l
          B
          sftp -b batch.txt -i ~/.ssh/id_ci -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new "$USER@$HOST"
