name: farpy-deploy
on: workflow_dispatch
jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Hide secrets if they ever echo
      - name: Mask secrets
        run: |
          echo "::add-mask::${{ secrets.HEALTH_KEY }}"
          echo "::add-mask::${{ secrets.FRONTEND_KEY }}"

      - name: Build sanitized bundle
        run: bash scripts/make_public.sh

      - name: SCP bundle to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          source:   "public/**"
          target:   "/opt/farpy/public"
          strip_components: 1
          overwrite: true
