name: Push payouts + purge CF

on:
  workflow_dispatch: {}
  push:
    paths:
      - "payouts.csv"          # adjust if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Upload payouts.csv to the server
      - name: Upload payouts.csv
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FARPY_HOST }}
          username: root
          key: ${{ secrets.FARPY_SSH_KEY }}
          source: "payouts.csv"
          target: "/opt/farpy/ops/"        # will place file at /opt/farpy/ops/payouts.csv

      # Purge only the two ops URLs at Cloudflare
      - name: Purge Cloudflare (ops URLs)
        env:
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
          CF_ZONE:  ${{ secrets.CF_ZONE }}
        run: |
          curl -fsS -X POST \
            -H "Authorization: Bearer ${CF_TOKEN}" \
            -H "Content-Type: application/json" \
            --data '{"files":["https://farpy.com/api/ops-log","https://farpy.com/api/payouts.csv"]}' \
            "https://api.cloudflare.com/client/v4/zones/${CF_ZONE}/purge_cache"

      # Log the deploy on the server
      - name: Log deploy in ops log
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FARPY_HOST }}
          username: root
          key: ${{ secrets.FARPY_SSH_KEY }}
          script: farpy-ops log "payouts updated via GH Actions: $GITHUB_SHA"
